const app = require("quik-server")
const cors = require('cors')
const express = require("express")
const http = require('http')
const silentRequire = require("./code/tools/silent_require")
const Gun = silentRequire('gun')
const path = require("path")

// 
// database server
// 
const databasePort = 8765
const databasePath = path.join(__dirname, "data", "database")
const gun = Gun({
    web: http.createServer(Gun.serve(path.dirname(databasePath))).listen(databasePort),
    // "file" is a misnomer, its actually a folder
    file: path.basename(databasePath),
})

// 
// webserver
// 
const webserverPort = 3000

app.use(cors())
app.quikAdd("quik-dom")
app.quikAdd("quik-backend")
app.use(express.static('./static_files'))

app.settings = {
    // default settings (all are optional)
    host: "localhost",
    port: webserverPort,
    // server can also be https (see: https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)
    server: http.createServer(app),
    websiteFile: "./web_server/website.jsx",
    codeFolder: "./web_server/code",
    computerGeneratedFolder: "./web_server/autogenerated.ignore",
    bundlerOptions: {
        outDir: "./docs",
    }, // see https://parceljs.org/api.html for options
    afterServerStarted: () => {
        console.log(`Server running on http://localhost:${webserverPort}`)
    },
}
app.start()
