const app = require("quik-server")
const cors = require('cors')
const express = require("express")

app.use(cors())
app.quikAdd("quik-dom")
app.use(express.static('./static_files'))

const port = 3000
app.settings = {
    // default settings (all are optional)
    host: "localhost",
    port: port,
    // server can also be https (see: https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)
    server: require("http").createServer(app),
    websiteFile: "./web_server/website.jsx",
    codeFolder: "./web_server/code",
    computerGeneratedFolder: "./web_server/autogenerated.ignore",
    bundlerOptions: {
        outDir: "./docs",
    }, // see https://parceljs.org/api.html for options
    afterServerStarted: () => {
        console.log(`Server running on http://localhost:${port}`)
    },
}
app.start()
